name: user_app
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.0.0
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  equatable: ^2.0.0
  flutter_login_facebook: ^1.6.2
  flutter_rating_bar: ^4.0.0
  flutter_svg_provider: ^1.0.3
  dio: ^5.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Noto Sans
      fonts: 
        - asset: assets/fonts/NotoSansMedium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansRegular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans.ttf
          weight: 400
        - asset: assets/fonts/NotoSansSemiBold.ttf
          weight: 600
    - family: Lato
      fonts: 
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
